version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # ソースコードをマウント
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  frontend:
      build:
        context: ./frontend
      container_name: react-frontend
      ports:
        - "3000:3000"
      environment:
        - REACT_APP_API_URL=http://localhost:8000
      volumes:
        - ./frontend:/app
        - /app/node_modules
      restart: always
